# Generated by Django 3.2.14 on 2024-01-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrack',
            name='refresh_token',
        ),
    ]
